### ISSUE TITLE
Spelling

### ISSUE THREAD

**Issue by tslott** [joelazar/wtfd#1]
https://github.com/joelazar/wtfd/blob/master/README.md#delete-it-when-it-served-it-purpose
served its*

https://github.com/joelazar/wtfd/blob/master/README.md#delete-it-when-it-served-it-purpose-1
served its*

**Comment by joelazar** [comment]
Fixed in: https://github.com/joelazar/wtfd/commit/80319a0429e3636c9de7fc514452650677951840
